[package]
name = "sigmaker"
version = "0.1.0"
authors = ["Exceptis#0001"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4.0"
iced-x86 = "1.17.0"
log = "0.4.17"
binaryninja = {git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev"}


